name: Release

on:
  push:
    tags:
      - '*'

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: ncipollo/release-action@v1

  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ "386", amd64, arm64 ]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Release mongo-healthcheck
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.20"
          sha256sum: TRUE
          release_tag: ${{  github.ref_name }}
          project_path: "./cmd/healthcheck"
          binary_name: "mongo-healthcheck"
          ldflags: -w -s
